ansible_become_pass: ENC[AES256_GCM,data:7MA41k6oHHMPGrdBOWSxclswS5a73TQd,iv:yAYSO8U9Q4vBpnzd5tu4EMapqdfEG31OrynjDjp/52k=,tag:vRAAHL7xzy5u3WgxTZL2VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSmEwcEtua3pxOVZtWHFZ
            TE5yV0NJd3NJb2taNmEwVTV1bjErakt4WERNCjJwRlJHbmpNbE9ZMllVdTRnTmJF
            VUxPUlRVZnlmWTJhRG9qYVlZV3J4eVkKLS0tIDhhRkFMdnFmNlQva3hJdTI0WUEy
            TDhPSWJZd3Y2Zi9jNHdZOHVYeTBtbUUKYulBrINKW4xgV6QxntANudIDrn1SMMcJ
            D39Xx0Aakmnmy4epikHr+opA9ydITnbntv0VNtS1BRcdRwT5P+KJRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:08Z"
    mac: ENC[AES256_GCM,data:rRRzljOSGOalkUN6NQZ8DN4mt5tVZ7Bi+oa7mSB+6OjrSn9DY/0IYXO5PPrtMJfAlhEMcaGAD5F2qLrZ9Hg6s80gG61sQErPX3ft/gZaPmHG0Y2zXDTIaLsA5ZVrqB04NRB+itkS7ZhPfPrJ9Ts2PDyAiZuCfUVcOVJmWzyhulY=,iv:12wuzcBUAP5lQdYhykeH/sJ++F39HzHkwQgL9IxvnsU=,tag:2OJUUJ3tlGruFflO8noZXg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
