apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kVW/18sMlwnWcJ+DtQV3mxvWxmsaJ4lV,iv:sfsaLbyW0qPN5VBDcNyEQC7BwnXXoUONoqiwFt16/IA=,tag:TtSsF9hFcu3F9hxtn4uJsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcFpHc2JYS25iRk5YNkJQ
            elZPUUtWbXFTUVc3VlhGcFdxZEVZVUZkSnpJCnJMSW9IVllvcTdFMnMyTG1aSDly
            ZDF4b3M1VU5ZRnRqQnlzb3JHOXZhYWcKLS0tIEk5Q2Fac3BiNXBJODZ0cUdoSXFX
            RHppa0RUME5aeWJlK21PR3FNRFJLTXMKPzAV4V5yFoFv2Jc2Cx0st1j03ozZQU+U
            t41Yw8VukfXmqPLIu2h5QR3VdgEGz3Fsb6JF6p9WpyZe4HA2YYxMpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:39Z"
    mac: ENC[AES256_GCM,data:u7gXZKorUp4kmZtUwdVnecuxr9k7MN2Y5CVHxqL5grHU+mIz0MP2Cf9lPTu+dNxytg5l+sWtcBR5FeYZ+itFH8AkK7ISKGpz+U1w4aoBVmquHDDi84K5+/4IyBVGC/7iscv/DjQLrqHzjvq+NsXD4+6AipC0GomLG4fIiQeOaDw=,iv:ayLcd1rsE//9FoRvhb5ktJfEm396IW4XJb71r/mMRgI=,tag:I8o/pujUFrQSWDQ3pzSsAQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
