apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:5PwAncfS1OyQqZblUXD4deUYTeUnkZfZ,iv:uSEhUkouCzSI/hiudLQFB5KjfCKHCvGJpd4YJuB3yGg=,tag:E/47h5ZvsOfxA2nGd7wEaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbXFqd2s3b0ozK0hnckVp
            OWNqSmpxWFBIb2lpQ04zaTRKeG0rM2FsYmpNCi9jN25TSkR0RXZvYlU3WlU5VUlW
            SHNYcG1qbWpnamtXRGUxcUZZZzRId2sKLS0tIG5nOE81NzQxcGZuL0YzTDg0YStB
            RXoreGg1bnp3T1lWRDhxb0lpOGJEdFEKCwRyBCD0Nv/l1/Yd10FNmNoV6i6GZQB/
            D8N7eoBS098jnLMvIxI9XmRAIQglE5OVnvZdsZ6lzbkbMZzap5o9fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T23:53:00Z"
    mac: ENC[AES256_GCM,data:FBOT1x0/n4/Zj7eRqzyX7HRPTRDl+/9bhyTRYBY/kitbmqWu/ed7PoHod18K+I6mp32UQsnPnfllttcRIBSa4tNZ+4gUpUQ7mud45BzL52KMcaMHtBESZLhJgLei53Db6XQp11uvlEQGNBGeJSdKr1T7vLATPkiiz4UsYniIoZg=,iv:zQQ/xclcv04wzm/JHdX2G3yhS5HiB/EEPB4Iw0yUXuU=,tag:5kCLaKX6LP2Jz+BcwuNtDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
