apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:c1MPXmzEiW4ftjvlMwDu4PuraYFxgH4Q/wIlA8mNxJ19X6qLtKuSNg==,iv:fV5UfOAaXX3Hn/Ug6Ux4MUNtRd9S3uwXP+UynUyRJgo=,tag:2xHnu9VHFbIrV9nULciibA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RnVKeW9ZSEthR1dJcjJZ
            cmZKWjJNNDlaM0tEZ3lWamp6MGxnRzRiR3pzCjdIL0l5WExWdW9sSzB6UG5zKzJH
            TkRyeUNkS0lSS1JMOTg3K1FFUHpJa28KLS0tIDhoME94eEt0TUZlRHJEN2p1cmI3
            NUtSSld6VUtWa01INC9abnhod2w5OEEKX5WsShYmZylbYqu3AZoaCL1M3ekk2IuO
            HbMsgJ8xd/V+VxHJaf3dr8XmMszT0OJg4YGWQjPF94nthvf7377XOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T23:53:00Z"
    mac: ENC[AES256_GCM,data:47OUKkzDd4Tdpq//o11Aja1n/V/90vKLsSQIrNcscblMvGNa5AAFfCSdiZ133UOis/Lqlgb3QuIkPtDBKBw5x+D9zS669dwRuFqBKIJ2vEnblk+vcO7hWo9hpNjz3Dsl9zAFzTI50fVGqiLdAVs1YRrwbfNv5WBZs+MxIMLkAVI=,iv:KKmwno9dFDh52gmlZlOr/VCznNCdjrNlrGMwtTYrSkM=,tag:orSYng0Qs9oAin2h8oHReQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
