apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:kXGD5wuxgyak6yyNlw/5Kk5PkxCNPmEkoW2xP0hs8gHq07b6bZzfPA==,iv:7najCKQ9uPkaD0MYgiqIFo5E7zhQcTInUUihvUVsImI=,tag:JZqYhc9JFtIplCUm9KzZeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcFBZbTBPT2plamdkUmEz
            OExUck1xelVMeVBHQmJCOW9YZzIwZWdHeXo4CmNtZ3B6bHc4TTdSa1FwRHEraTE2
            TUFxV29jR1IxUjFuZnZIOTgvME4ySzAKLS0tIDJvaE5RdW11ZDFaWGhYdUc0emln
            YzBwYkhuTHBWaEE1U2VzSktTMTBKNXMK7IFWZWLvpsiuXijHT1AjaYb4vdFTLwbB
            eu+nKhdP13w3P/e26cnMTpXkkKR9lV6LAUHZ5KnHwpLoir9pOaJ0Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:39Z"
    mac: ENC[AES256_GCM,data:/vOnnfq36soSTS2BDAxUS9zbsvXBPEzVXv5T3MbK0XiYfjfk/zh+UrLvlls6i+v2rJ8SC5+4AzT05SKkF+OfvL0d8e+gsUibAxbCx9zWUKkR/T+o0NtWspg1c+KxR/rH7YATSQBUVwgdoUuDv034im8ZN6Ky8SVXV7Xwr28mWLk=,iv:vKdsByrhD1KK7nMo6uMC7l0N7CMc1P+J2zAkOvYsRwI=,tag:/w4GoOeuSLUEQzN+ejQ0QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
