apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:DgN/DBs5/njnZDT7OQjJAAUaDTQSR6BsSaeH3zOfhCFBDfKf33XSyQ==,iv:235Z3+bTOda9jybd+CFQd/XtIjYrUXa0BK1dP7syOeM=,tag:Wi0AKrsCg/NfouzATEJGag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TXZRYU1yOVpqR2Q4bWIw
            WDFzR2toUkd6eUdXUzcweEozWVJjNHMzQ2hvCkhKSnh0UzFPNyt3WTZBd1lFMTFJ
            c00weFZYRk5VbDZxa3NiNTVPTjRaYW8KLS0tIExWY2tuM0FzTlNJSTliNUw4bTJT
            bXZQL1llZzJKY3RiLy9zRFhsY3A0UTgKGo+bSsvyoRFIn3oDPIAKarNW1wtQzqqF
            wkeAlc1Z6lg8cEO8fi8VIEWTb+kNOVJu2KHAp7RNuZfPvAvj3C8G4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:39Z"
    mac: ENC[AES256_GCM,data:4mGbK/YqMZ6aqf8U3lmH/uW5vlSgJtKBFFxQDi9OniOS7OtwuwZbvnnhRJq1Fhm5DuacUwYAYWSFPyO/kFeXYvkUiN4RviZ3pVgfTJj/d1yfgpnzusyvu0qYgkQ9Nch+jYcWImntICkEW1WqYqWEb3rSsawLTrbL2AbpIAsbNqE=,iv:BaFEQWyS9uXTsNBEDLGbwLBc6fXVrgIt2BoFR2T4GRU=,tag:gh5I8M5pdLuXv/EuP7nKYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
