apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:mC42WhJyZ4pJwsbbgqqdPpYRUjX/6hf/+M0B9TWjzOlS7nMN4SG1Lw==,iv:s90hgpjiUZ6r98mB921UziZmFL3E/CUgZKU8/UXYbks=,tag:iDXvZ+qv9ymD5ksORLZ9LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNGlsK1ZCR3pPZkZOVDJW
            Z1daYkNsWEc0c1ZSY3dMYkVhVFFsTjNxZ25nCk5PK2xDdmpJTkRVcGVSNnBMM3Y0
            OEFrQzFYZVJKN2ZKckFvV1lOQ0I3Q0kKLS0tIFo3QmtiKzhzTGlNQ0pPZ0lrSWpU
            TDlTUGgrczlraG85Ymlvbk1SbXZaVUkKrj/yG+OfXszKiSUnYdt8zdgB7nELuirz
            fDsZ8LKvScTe0mwRRKg5MSYhOYNiy2aeb6kbJO3lb/t53e9x48LOqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T23:53:00Z"
    mac: ENC[AES256_GCM,data:EJHtfVDoNIuN+Aa/zdRfqsOyyvyzhLn+E/JqgbTe8xRG+SwhGHw701SeQp2hXZy14VWvu1b8dSOeqGWdJOQqb8FJoMuQ7GxnHnQuXSLfrfDGkt+DgiVDd+mhJSCuqrN9WzrrAN+B+S7xGT83lk8eZHpxhX3S7NnWaE6z1LoVDjo=,iv:Ie3VoKWpZFyaHiqb9oreJoZmj24RFMfIKNaVO1v1H+U=,tag:GQYTECfN6a9Udycq7vMnzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
