apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:YFVvKR2MwXleM/by,iv:snrMCmq7/7T1DVe/EgBTACKyb8dL9jUinLSbAwfYYto=,tag:qWyniWEFACzjJ4uS80T3DQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTVppdld3T21vbGFLNzZX
            V2FzbXhTN3pybUIvbEVHbVBPbmhPOW5tZ2hjCmhtcmo0anF6ZXh0OWZldDF5U3ZP
            QkZ6c056bGowRkdXOElCRTA3bC9MNGcKLS0tIFZzZTMrYk1nQVNhUUZXRndMOXN1
            dnJiM2lSTTAvREtOUy85djZMdmYrMzQKoKBpR/KtD2Np5yXeIC9AZiur5IzU2kY6
            MFlhWvZzuPNMmKaXG2/HmYps+QXfLZaKr1KTkAcbJdmY69h5JWsYog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:38Z"
    mac: ENC[AES256_GCM,data:/m9+TPgTvaPl5yay3PMfIyeyRkfuYZAhmejbis6uuD4tWGDSSp4292Mn6MdKnqdZNhVR4xsRgrDGtMjAzRRrayBJIbvgNMFAcruLJQvWsdrw1Vmm29gNPzqAtvRbRUBwpD/rZD/apeoeKZw1RFZ7uYY5AbPOpTVue1UPdOB7WpY=,iv:n5/vSJK5SVzvmIb/zbt6TynoC2iGUOkiEVEm2yu2G/I=,tag:KRhDLYrllATNmlARlslOjw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
