apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1J40G2Masz221/hCQYRRu4w=,iv:hzbCIfqjqbD6cPhcbdkzyxgCR7FbIl+7N5kkTN0ea0I=,tag:EqWAi+gPIgakCEDT7ZegaA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:hMmxUQX4JjSh8ZZ114QuJqq52NNMBj70RKgQdRdiF93H9HZU,iv:395OSWyz7VCZAwycPc4YvoHTNpfrnuNwQsnKH7WQfIo=,tag:BDeRfZU1QTwERYBXMgHwvA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4eDr3pq0bnmGZg==,iv:G1uyOpd40JJOq1i0knib3cTPEZb3R/S6eMbieztsGCc=,tag:QAz4hvyWn2rRJz9vlgJZfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd2VYWW9sVnpDYlFoRkN6
            eWI0RFVuSDYreWRTeDB3NVpGT1ZwMXRoVEhvCldXN3RlRkkraGQ2S3dGT09scUhI
            MXV6b05SQTJJcjI4VVgxeXd3T1pmaE0KLS0tIElSUnJpdzFkWWlieSs5RDNiR25x
            Nit4S2Q1KytNV0NVN0p5b28vVDNnekEKx/rFaJLvLM5bOTCrcmflz+qeakJZctTk
            s8DOEQXtJt7/71rwvba1EknURma6snIkzu0/spOui14yzMdJiEALQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T23:53:00Z"
    mac: ENC[AES256_GCM,data:b8toD2BV57PzqqKpz+kdf+Mecs3xx4UnSXTUIm1oAVomwvK44ift0QzN3y+Maf2YwthZFNiSQ2H2/GkSpOdJlSpvunMcfdGA9s0mJjRxvHVlXpYZk00eHe3SvBUzJYm9nAxRFqsYRj6UZD5dmzJERFxmCR0ylwLJ5CO2DQq08v8=,iv:/pGMSVvDf9vQuwAOW0vgMow9YfloJmLoPFO7oQtiAdQ=,tag:8c6iFQoY8EJbR8Crwo58kg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
