apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YU/7gvayTM2WFYPjSBH77U4=,iv:v5jymh+LPSZvXLnWjXgziTb6mDXrrrixx85nSexnpn0=,tag:dYocS35i8UoXshBephWMbA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Rwl6jKgJnAhm4IXJ+OLas/Fz++ONismH24K7JbbPxGFU5KoV,iv:u9KamCYIhlQXrgj29zDGT3y4waAqI/Cq32AkwkisEY8=,tag:4WDa3PKi45afzDJGbNeDqg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:P/YIlm6yZkkxGQ==,iv:IIUaSNVK6Or0aeAibvEF6LtNkzR+Ouot3kVA8CylB0Q=,tag:L//CSfe8QRTYuSXTk4JcQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMDlKeFg1WlhqMWgrd3lM
            QjUrYmJ1MlFlUTFSV0pid3Jxb01oaGxmV1UwClN0c0lkNWx2MC9ONE5pRHEyN0d2
            VEYrOUNwQmdpOWpmekIwZWRVN2FkOXMKLS0tIFlrUDJzcGw0WUUrZUxOd0RDZ1BW
            YlI3aUlhcEtmeklGNnZUdmNrTTVyaGMKZ9j/FNls+Ms7OgHjOgMh0g+XQqS5wxzf
            OwYnlXAXcB3ZVc8j0w7FJM+1q3K3ZZKk6yllXUshijWrVURfRVleEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:38Z"
    mac: ENC[AES256_GCM,data:F6XjvwC1ETPG6xA2LoHrEx8Lr61UTRjwAzpsg8ZcEyfLfAZ4yXmick8/+TB5i+0+ltFcGQROAU8cor/gT/SRG4csAYjQCBP+ZobhpjyX45KylkxTgxrFQ6PzYOhm8Njlx7HWDQPPmvBF0XcUqQfZzYiqy6WOntbFz/7Qk/IlQ0U=,iv:UQWZ1NfM5yiQeDKJG3TnxaLpzRHCeJuFuBBqrNziuj0=,tag:2F2oKlCX1dlWepPBUCW7BQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
