apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:mhd3DKDgryZ/ORbn,iv:Xtsm0RuTIjpCpawj4Zt9mUvpoe8vye8LMgH0DsJR7E4=,tag:EdwMZWylMERq1Ntdn0TWVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRlhLNjUvdnI3b1BuTzI4
            OUtDeXZta0RGUGhNU2tCSFhoUlo2VENRR0RrCisvUHExWnpoSGdMWHZPMEs0Rmtq
            U2xlNVJPTGs0NlhTaDkwSE9FY000UjQKLS0tIDBYTGFXSjJVVERONlVzVm01UGV2
            MlNkVGVpUUUwUXFEOTZNc1RrTk9IeGMKJ0yC2Qd9/VlxBLAwEN4bVhCiRna7K+LZ
            FqhGsquhP+TXFnK3uA6lxLS8CmTvdCAbcaV9zn1UgoFVKAIVKZkG4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T23:53:00Z"
    mac: ENC[AES256_GCM,data:fsVciTKWGwE3kmVmkpDdb6LAhO4BrZqRqsz+IAeq2yeRmX8q/FCwkZ34pqL42wJbCX/90Cq2mOQ9envEx+lgjlk7iT+0y9Fb5dPKSecejX50CCebqG6naGH3HNawsT1QVBeWsYpJWRVYP1pKsm/PmeAiIsPW1YY5De2tcFxDEwY=,iv:dqW1k+w9C1RYTWRoCz5Nghf3IUw2nMHgGhKgepFidDU=,tag:mLrQUoFUrBJaoR53CVbZRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
