apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0TpaZNdcsguYQy87sqnV7rZq0Ef3sJDBl40BJibYAxuk0jHo,iv:Y9e8lejCnsO+lv2ICNquPHw3c6B4f+e7KrIKjgoG0yU=,tag:MdvjAfnsGUTxhgQ5+oaD5w==,type:str]
    credentials.json: ENC[AES256_GCM,data:fIx1VcSv3xR/RJ7K9YfgYoBjeMMGIZ3DNdy0N6OfSbXfDXGSk3CnfuLxswC+84Od2ptlOQdXem2GxBs5KiUyo1Yg2NMxlSWZzkDS0cLa3GKZtbvY08Z7F94caDaw2P0BprI0wc1SxOFdHX490VUUKQvQkpXQEzgMUSzfUb5Vmg5Z+6ACoEWGZc8Zi9aqIjzoDS2Bp0gzRcg/ZbOfXeOiB/J8Sqxt3ulbvTDjzFExBQ==,iv:SVnU5rlPMP84ZJ9KlR4stDCBQIs+CUOQ4DX/tCu5oxs=,tag:2t41OgfAwYUIyh0kiIFqpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcnJaUlp3YUhMSHdpbFFu
            OWNPK1ZPUklWNzJpRmxubjRvU0dmTmt2U1drCjZ0MGtnWUd3aGpVUDdPTTh2Uisv
            WTB2SHlQSW1LY0tYV0tVVjM3K3B3QlkKLS0tIHhHV3VFbUluNGtyYjdEenlpaG8z
            S0NKYldOVEZqNmRYdXAvV0d0TlpoazAK3hr6LvhOcyYLqEZ+QzCf2X9ZZ0EQSPMY
            gPk9mKDlusgbGI1Ux+QkPmW8heA7Ef4hkaCXfI2rrQ2ioySeu+etIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-15T23:53:00Z"
    mac: ENC[AES256_GCM,data:9s8gMpV8JkDbo/BjSQ+7KO97elnPYGb/2QV9mpumcGiIgApncf+NZ6ufCXXx5iO3Ihbym6BS5SpmC0ShPSy2ICyFyvDYghVLjvci7gXMd0hyjq22P/Kxgumx2WLGZw6H+t9CPVL4hx+DWzlxZ6a04SweluwGTJStu2GIVTxBszc=,iv:QSVsR10lnhpVvKjUviAL02zUDEpK13tyvXK5ti+58CE=,tag:w2wyGsDKqr3D7QIg164E5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
