apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:6iJ8zl92QPf3Ek0ug6Ulyd4DsDMd0TD7BkAI8m8pB9ocBuTN,iv:0fyZC+dAoSYCJ2xNsJo9RDfYZlxSA5+4zpjxMdmnnow=,tag:yKL4ClSWmVQTLkrX9K7lOg==,type:str]
    credentials.json: ENC[AES256_GCM,data:TxHYomqjmhqe9vByiTfLmKggYCbHBP07pf4QhSCkWWazjaHNRWcqVbcDbK40ygvCF31ACggVmEl+fLiFccqEELAmOQUPWPNU5hGGCHW2bxbZv7B7YsZlOQE/L/Q034zP2reAalP23Y8c2yudslNdAjEYvt75FBtOtuMiEam22jAsGnJzGBXw9dS4O9GnJRS3M9SXFlKc52PAYGvOJz4ptYjixupJN+oQ2LzkSIqU1g==,iv:9utMz+5sKlOjdQkzHul7mCtj8IbFs5yIYm24/PjDa2Q=,tag:xV32TlbZDtmrF7/XWXRV8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wnjz2pk5jeeuqlxnmwut6pzmhjymy553p9pcrkxgy4j7rupc8egsj8dw9l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZE0vYlFZR1liMXdtOFBX
            dUI0N3VINnc4bXNkc25WNVN1MTNNTzhpM3pZCk1QS01XbnBCWGNrV3hnQU5rMGc2
            dkJQQUxySFVlSEJ2MHcxUGFWNWpteW8KLS0tIHNNc080Tnp0LzBqdXBNUE1zVVUy
            MkNuMll3dng1aktPQjkyM0FUbW1yS0EK7WCJzYnD1hhE5nXzRb9XLrD4G/1cA3vA
            UPqMQmePB1eIPkUz8d6EnXGNpISf5GqTxo4ht0LJ4ImWXXjm+7gckQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-16T00:07:39Z"
    mac: ENC[AES256_GCM,data:1o+fhL1QbGIA4s9Unbayz3k2B51yBNTOcyl3XUxiGaW5YgautSp+OfVdUybGLBRkNJe6SsXS0uHH3mJ6Aa8Tn5FFKOCRKBjfQP5hI6fhuC9/j+OrqIqPTLNFZMk2LcAbwb0+o1rwmgkZk8A17xlzuzGFBh987KRAstsdR7B3SUo=,iv:CwX0so6Tb1FyPE/kK2QPwab8PXrqbo/opylckS+HDkY=,tag:nkFI4rp1BuBb1cBEuap2Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
